package Votaciones;

public enum NombreProvincia {
    BUENOS_AIRES,SALTA,CORRIENTES,CHACO,FORMOSA,SAN_JUAN,SAN_LUIS,JUJUY,MISIONES,TUCUMAN,SANTIAGO_DEL_ESTERO,SANTA_FE,ENTRE_RIOS,CATAMARCA,CORDOBA,LA_RIOJA,LA_PAMPA,NEUQUEN,RIO_NEGRO,CHUBUT,SANTA_CRUZ,TIERRA_DEL_FUEGO,MENDOZA,
}
